.TH scr 1 "" "SCR" "SCR"

.SH DESCRIPTION
The Scalable Checkpoint / Restart (SCR) library enables MPI applications
to utilize distributed storage on Linux clusters to attain high file I/O
bandwidth for checkpointing and restarting large-scale jobs. With SCR,
jobs run more efficiently, recompute less work upon a failure, and reduce
load on critical shared resources such as the parallel file system.

SCR caches checkpoint files in storage local to the compute nodes, and it
applies a redundancy scheme such that files can be recovered in the event
of a failure. When a failure occurs, the current run is killed. If there
are sufficient spare nodes and time remaining in the resource allocation,
another run may be restarted from the cached checkpoint files. Otherwise,
the cached checkpoint files are flushed to the parallel file system, and
the resource allocation is released. With this approach, file I/O
bandwidth scales linearly with the number of compute nodes. On large
clusters, SCR is often 100x to 1000x faster than the parallel file system.

.SH SEE ALSO
\fISCR User Manual\fR
.LP
\fBscr_srun\fR(1), \fBscr_halt\fR(1), \fBscr_prerun\fR(1),
\fBscr_postrun\fR(1), \fBscr_index\fR(1)
