.TH scr_prerun 1 "" "SCR" "SCR"

.SH NAME
scr_prerun \- run before an SCR job to initialize compute nodes

.SH SYNOPSIS
.TP
.B scr_prerun [-p prefix_dir]

.SH DESCRIPTION
The \fBscr_prerun\fR command must be run before launching an SCR job on
a set of compute nodes for the first time.  It executes various tasks
to prepare the compute nodes for the SCR library.  The command must be
run from within a SLURM job allocation. The command does not need to be,
nor should it be, run before a restart attempt of SCR job within an allocation.
.LP
A job script must check that \fBscr_prerun\fR returns with an exit code of
0 before it may continue.  If a non-zero exit code is returned, the command
failed, and the job script must exit immediately.
.SH OPTIONS
.TP
.BI "-p " prefix_dir
Specify the prefix directory where SCR may read and write checkpoint
directories.

.SH EXAMPLES
.TP
(1) Instruct job 1234 to exit after completing its next successful checkpoint:
.nf
>> #!/bin/bash
>> ...
>> scr_prerun -p /p/lscratchb/username/run1/checkpoints
>> if [ $? != 0 ] ; then
>>   echo "ERROR: scr_prerun failed"
>>   exit 1
>> fi
>> ...
>> srun ...
.fi

.SH SEE ALSO
\fISCR User Manual\fR
.LP
\fBscr\fR(1), \fBscr_srun\fR(1), \fBscr_halt\fR(1),
\fBscr_postrun\fR(1), \fBscr_index\fR(1)
