#!/bin/bash
# This applies yapf and docformatter to SCR python files.

# https://github.com/google/yapf
# https://pypi.org/project/docformatter/

#python3 -m venv --system-site-packages env

source env/bin/activate

#pip install ClusterShell
#exit 0

#pip install --upgrade pip
#pip install yapf
#pip install --upgrade docformatter

set -x

which yapf
which docformatter

yapf -i python/*.py python/*.py.in
yapf -i scripts/python/setup.py
find scripts/python/{scrjob,commands,tests} -regex '.*\.py' -print | xargs yapf -i
#find scripts/python/scrjob -regex '.*\.py\.in' -print | xargs yapf -i

docformatter --in-place python/*.py python/*.py.in
docformatter --in-place scripts/python/setup.py
find scripts/python/{scrjob,commands,tests} -regex '.*\.py' -print | xargs docformatter --in-place
#find scripts/python/scrjob -regex '.*\.py\.in' -print | xargs docformatter --in-place

#git clone --depth=1 https://github.com/google/yapf.git yapf.git
#PYTHONPATH=yapf.git python3 yapf.git/yapf python/*.py python/*.py.in
