#!/bin/bash
#USAGE:
#Set SCR_PKG, SCR_BUILD, and SCR_INSTALL to fit your system
#Run with output sent to the first command line argument
if [ $# -ne 2 ]; then echo "This script takes one argument: the test to run and the path to the output file"; exit 1; fi

# set SCR_PKG to the directory where SCR is cloned
# set SCR_BUILD to the directory where SCR should be untarred and built (this will be removed with rm -rf)
# set SCR_INSTALL to the directory where SCR is installed
if [ -z "$SCR_PKG" ]; then export SCR_PKG="/g/g0/becker33/scr/scr"; fi
if [ -z "$SCR_BUILD" ]; then export SCR_BUILD="/g/g0/becker33/scr/build"; fi
if [ -z "$SCR_INSTALL" ]; then export SCR_INSTALL="/g/g0/becker33/scr/install"; fi
if [ -z "$SCR_LAUNCH_DIR" ]; then export SCR_LAUNCH_DIR="/p/lscratchd/becker33"; fi

echo "_____________________________________________________________________"

rm -rf ${SCR_BUILD}
rm -rf ${SCR_INSTALL}
mkdir -p ${SCR_BUILD}
cd ${SCR_BUILD}

# Linux build instructions
export CFLAGS="-O3 -fPIC "
export CC=gcc
export MPICC=mpicc

cmakeopts="${SCR_PKG}"
cmakeopts+=" -DCMAKE_INSTALL_PREFIX=${SCR_INSTALL}"
cmakeopts+=" -DSCR_RESOURCE_MANAGER=SLURM"
cmakeopts+=" -DSCR_MACHINE_TYPE=0"
cmakeopts+=" -DSCR_FILE_LOCK=FNCTL"
cmakeopts+=" -DSCR_CACHE_BASE=/tmp"
cmakeopts+=" -DSCR_CNTL_BASE=/tmp"
cmakeopts+=" -DSCR_CONFIG_FILE=${SCR_PKG}/scr.conf"
export cmakeopts

echo $cmakeopts
cmake $cmakeopts
make VERBOSE=1 -j4
make install

echo "_____________________________________________________________________"
echo "_____________________________________________________________________"
echo "_____________________________________________________________________"

cd ${SCR_INSTALL}
cp ${SCR_PKG}/scr.user.conf ${SCR_INSTALL}/.scrconf
cd share/scr/examples
make

echo "_____________________________________________________________________"
echo "_____________________________________________________________________"

# run the TEST
# must be run on a machine with python in the same location as on the target machine
cp ${SCR_INSTALL}/.scrconf ${SCR_LAUNCH_DIR}/.
cd ${SCR_LAUNCH_DIR}
msub -V -q pdebug -l nodes=4 -m be -j oe -o $2 ${SCR_PKG}/testing/$1
echo "Submitted a batch job to run $1 on 4 nodes with output sent to $2."
echo "You should shortly receive an email notifying you that the batch job has been submitted."
echo " You will receive another when it is completed"
echo "In the meantime you can monitor the output using \"tail -f $2\""

