#!/bin/bash
# set SCR_PKG to the directory where SCR is cloned
# set SCR_BUILD to the directory where SCR should be untarred and built (this will be removed with rm -rf)
# set SCR_INSTALL to the directory where SCR is installed
if [ $# -ne 1 ]; then echo "This script takes one argument: the number of minutes requested for the interactive testing session"; fi
if [ -z "$SCR_PKG" ]; then export SCR_PKG="/usr/projects/SCR/scr-1.1-8.cray.dev/source/working"; fi
if [ -z "$SCR_BUILD" ]; then export SCR_BUILD="/usr/projects/SCR/scr-1.1-8.cray.dev/source/greg_build"; fi
if [ -z "$SCR_INSTALL" ]; then export SCR_INSTALL="${SCR_BUILD}/install"; fi

# commands to debug various items
#export TV=/usr/global/tools/totalview/v/totalview.8X.9.9-1/bin/totalview
#export TV=/usr/global/tools/totalview/v/totalview.8X.8.0-4/bin/totalview
#export TV=totalview

# To use SCR_PRESERVE_USER_DIRS features, you'll need DTCMP, which in turn needs LWGRP
# NOTE: one must use MPI-2.2 or newer to compile LWGRP and DTCMP
# e.g., use mvapich2-2.0 or openmpi-1.8.4 or later
# fetch and build dependencies (LWGRP and DTCMP)
${SCR_PKG}/buildme_deps

# various CFLAGS for different builds
# build the dist tarball
export CFLAGS="-g -O3 -Wall -Werror -DHIDE_TV"
export CFLAGS="-g -O3 -Wall -DHIDE_TV"
export CFLAGS="-g -O0 -Wall"

# BGQ build instructions
#export CFLAGS="-g -O0 -Wall -Werror -DHIDE_TV -I/bgsys/drivers/V1R1M2/ppc64/comm/sys/include -I/bgsys/drivers/V1R1M2/ppc64 -I/bgsys/drivers/V1R1M2/ppc64/spi/include -I/bgsys/drivers/V1R1M2/ppc64/spi/include/kernel/cnk -I/bg#sys/drivers/V1R1M2/ppc64/comm/xl/include"
#export configopts="--with-machine-name=BGQ --with-scr-config-file=${HOME}/system_scr.conf --with-scr-cache-base=/dev/persist --with-scr-cntl-base=/dev/persist --with-file-lock=none"
#export scrversion="scr-1.1-8"
#cd ${SCR_PKG}
#make distclean
#./autogen.sh
#./configure --prefix=/usr/local/tools/scr-1.1 $configopts
#make dist

echo "_____________________________________________________________________"

# Linux build instructions
#export CFLAGS="-g -O0 -Wall -Werror -DHIDE_TV"
#export configopts="--with-scr-config-file=/etc/scr.conf --with-yogrt --with-mysql --with-dtcmp=./deps/install"
export CFLAGS="-g -O0"
export configopts="--with-scr-config-file=/etc/scr.conf --with-yogrt --with-mysql"
export scrversion="scr-1.1.8"
cd ${SCR_PKG}
make distclean
./autogen.sh
./configure --prefix=/usr/local/tools/scr-1.1 $configopts
make dist

echo "_____________________________________________________________________"

# check that a direct build works
#make

echo "_____________________________________________________________________"

# unzip the dist tarball, configure, make, make install
rm -rf ${SCR_BUILD}
mkdir ${SCR_BUILD}
mv ${scrversion}.tar.gz ${SCR_BUILD}/.
cd ${SCR_BUILD}
tar -zxf ${scrversion}.tar.gz
cd ${scrversion}
./configure --prefix=${SCR_INSTALL} $configopts
make -j4
make install

echo "_____________________________________________________________________"

# cd to examples directory, and check that build of test programs works
cd ${SCR_INSTALL}/share/scr/examples
export OPT="-g -O0"
make
#cp ~/myscr.conf .scrconf

echo "_____________________________________________________________________"

#mpicc -g -O0 -I${SCR_INSTALL}/include -I. -o test_api test_common.o test_api.c -L${SCR_INSTALL}/lib -lscr -lscr_base -lscr -lscr_base -L/usr/local/tools/zlib-1.2.6/lib -lz

echo "_____________________________________________________________________"

# get an allocation
mxterm 4 32 $1
echo "Requested mxterm allocation for 4 nodes, 32 processes, for $1 minutes."
echo "An interactive window should appear shortly, dependent on current system usage"
