#!/bin/bash
#USAGE:
#Set SCR_PKG, SCR_BUILD, and SCR_INSTALL to fit your system
#Run with output sent to the first command line argument
if [ $# -ne 2 ]; then echo "This script takes one argument: the test to run and the path to the output file"; exit 1; fi

# set SCR_PKG to the directory where SCR is cloned
# set SCR_BUILD to the directory where SCR should be untarred and built (this will be removed with rm -rf)
# set SCR_INSTALL to the directory where SCR is installed
if [ -z "$SCR_PKG" ]; then export SCR_PKG="/usr/projects/SCR/scr-1.1-8.cray.dev/source/port/working"; fi
if [ -z "$SCR_BUILD" ]; then export SCR_BUILD="/usr/projects/SCR/scr-1.1-8.cray.dev/source/port/working-dist"; fi
#if [ -z "$SCR_BUILD" ]; then export SCR_BUILD="/usr/projects/SCR/TR-installs/scr_dw_with_source"; fi
if [ -z "$SCR_INSTALL" ]; then export SCR_INSTALL="${SCR_BUILD}/install"; fi
#if [ -z "$SCR_INSTALL" ]; then export SCR_INSTALL="/usr/projects/SCR/TR-installs/scr_dw_with_source/install"; fi
if [ -z "$SCR_LAUNCH_DIR" ]; then export SCR_LAUNCH_DIR="/lustre/ttscratch1/becker33"; fi


echo "_____________________________________________________________________"
rm -rf ${SCR_BUILD}
rm -rf ${SCR_INSTALL}
mkdir -p ${SCR_BUILD}
cd ${SCR_BUILD}

# Linux build instructions
export CFLAGS="-O3 -fPIC "
export CC=cc
export MPICC=cc

cmakeopts="${SCR_PKG}"
cmakeopts+=" -DCMAKE_INSTALL_PREFIX=${SCR_INSTALL}"
cmakeopts+=" -DSCR_RESOURCE_MANAGER=SLURM"
cmakeopts+=" -DSCR_MACHINE_TYPE=0"
cmakeopts+=" -DSCR_ASYNC_API=CRAY_DW"
cmakeopts+=" -DWITH_DATAWARP_PREFIX=/opt/cray/datawarp/2.1.8_g2de47e3-2.27"
cmakeopts+=" -DSCR_FILE_LOCK=FNCTL"
cmakeopts+=" -DSCR_CACHE_BASE=/tmp"
cmakeopts+=" -DSCR_CNTL_BASE=/tmp"
cmakeopts+=" -DSCR_CONFIG_FILE=${SCR_PKG}/scr.conf"
cmakeopts+=" -DWITH_PDSH_PREFIX=/users/becker33/pdsh-2.31"
export cmakeopts

echo $cmakeopts
cmake $cmakeopts
make VERBOSE=1 -j4
make install

echo "_____________________________________________________________________"
echo "_____________________________________________________________________"
echo "_____________________________________________________________________"

# cd to examples directory, and check that build of test programs works
cd ${SCR_INSTALL}/share/scr/examples
cp ${SCR_PKG}/scr.user.conf ${SCR_INSTALL}/.scrconf
export CFLAGS="-g -O0"
make VERBOSE=1

echo "_____________________________________________________________________"
echo "_____________________________________________________________________"

# run the TEST
# must be run on a machine with python in the same location as on the target machine
#sed -i 's|^#!.*$|#!'`which python`'|' ${SCR_PKG}/testing/TEST
cp ${SCR_INSTALL}/.scrconf ${SCR_LAUNCH_DIR}/.
cd ${SCR_LAUNCH_DIR}
sbatch --export=ALL -p standard -N 4 -t 30 -o $2 ${SCR_PKG}/testing/$1
echo "Submitted a batch job to run $1 on 4 nodes with output sent to $2."
echo "You should shortly receive an email notifying you that the batch job has been submitted."
echo " You will receive another when it is completed"
echo "In the meantime you can monitor the output using \"tail -f $2\""

