# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats:
  - pdf
  - epub

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
      # pip-compile was used to generate the requirements.txt file to enable
      # reproducible builds.
      #
      # If adding or updating top-level dependencies, update requirements.in and
      # then overwrite existing requirements.txt with results of pip-compile.
      #
      # If simply wanting to update transitive dependencies to pin a new
      # reproducible build, then overwrite existing requirements.txt with
      # results of pip-compile.
      #
      # https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pin-your-transitive-dependencies
    pre_install:
      - python -m pip install pip-tools
      - pip-compile --strip-extras -o doc/new_requirements.txt doc/requirements.in --upgrade

# Build user documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/rst/conf.py
  #fail_on_warning: true

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  # If needing to update for pinning a new reproducible build, then overwrite with
  # results of `pip-compile` command above.
  - requirements: doc/requirements.txt
